"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RecoilRoot } from "recoil";
import { SessionProvider } from "next-auth/react";


const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <RecoilRoot>
        <SessionProvider>
        <body className={inter.className}>{children}</body>
        </SessionProvider>
      </RecoilRoot>
    </html>
  );
}


